frams/urls.py
from django.contrib import admin
from django.urls import include, path
from . import views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('signin/', views.signin, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('signout/', views.signout, name='signout'),
    path('progoffice/', include('progoffice.urls')),
    path('teacher/', include('teacher.urls')),
    path('activate/<uidb64>/<token>/', views.activate, name="active"),

    path('reset_password/',
     auth_views.PasswordResetView.as_view(template_name='authentication/password_reset.html'), 
     name="reset_password"),
    path('reset_password_sent/',
     auth_views.PasswordResetDoneView.as_view(template_name='authentication/password_reset_sent.html'),
     name="password_reset_done"),
    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name='authentication/password_reset_confirm.html' ),
     name="password_reset_confirm"),
    path('reset_password_complete/',
     auth_views.PasswordResetCompleteView.as_view(template_name='authentication/password_reset_done.html' ),
     name="password_reset_complete"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

progoffice/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='office_home'),
    path('addteacher/', views.addTeacher, name='add_teacher'),
    path('completesignup/', views.completeSignup, name='complete_signup'),
    path('pendingregistrations/', views.pendingRegistrations, name='pending_registrations'),
    path('deletependingreg/', views.deletePendingReg, name='delete_pending_reg'),
    path('teacher-attendance/', views.teacherAttendance, name='teacher_attendance'),
    path('teacher-face-attendance/', views.teacherFaceAttendance, name='teacher_face_attendance'),
    path('teacher-fingerprint-attendance/', views.teacherFingerprintAttendance, name='teacher_fingerprint_attendance'),
    path('teacher-report/', views.teacherReport, name='teacher_report_admin'),
    path('addstudent/', views.addStudent, name='add_student'),
    path('student-attendance/', views.studentAttendance, name='student_attendance'),
    path('student-report/', views.studentReport, name='student_report_admin'),
    path('generate-teacher-csv/', views.generateTeacherCSV, name='generate_teacher_csv'),
    path('generate-student-csv/', views.generateStudentCSV, name='generate_student_csv'),
    path('course-report/', views.courseReport, name='course_report_admin'),
    path('generate-course-csv/', views.generateCourseCSV, name='generate_course_csv_admin'),
]

progoffice/models.py
from random import random
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import cv2
from PIL import Image as Img
from io import BytesIO
from django.core.files import File
import face_recognition
import numpy as np
from django.core.exceptions import ValidationError
import pickle
import base64

from . import myFields
from django.contrib import admin
from django.utils.translation import gettext_lazy as _


class Teacher(models.Model):
    Teacher_Statuses = (
        ('V', 'visiting'),
        ('P', 'permanent'),
    )
    Teacher_designations = (
        ('P', 'professor'),
        ('AsP', 'associate professor'),
        ('AP', 'asst. professor'),
        ('Ins', 'instructor'),
    )

    def check_faces(face_img_obj):
        pilImage = Img.open(BytesIO(face_img_obj.read()))
        img = np.array(pilImage)

        try:
            img = cv2.resize(img, (0, 0), None, 0.25, 0.25)
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            faces = face_recognition.face_locations(img)
        except:
            raise ValidationError('Error processing the image, please upload a clear picture with face focused')
        if len(faces) < 1:
            raise ValidationError('No faces detected')
        elif len(faces) > 1:
            raise ValidationError('Multiple faces detected')
    
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    teacher_name = models.CharField(max_length=50)
    teacher_designation = models.CharField(max_length=4, choices=Teacher_designations)
    teacher_status = models.CharField(max_length=1, choices=Teacher_Statuses)
    face_img = models.ImageField(upload_to='teachers/faces', default="", validators=[check_faces])
    face_encodings = models.BinaryField(null=True)
    right_thumb_img = models.ImageField(upload_to='teachers/fingerprints', default="")
    right_thumb_keypoints = models.BinaryField(null=True)
    right_thumb_descriptors = models.BinaryField(null=True)
    right_index_img = models.ImageField(upload_to='teachers/fingerprints', default="")
    right_index_keypoints = models.BinaryField(null=True)
    right_index_descriptors = models.BinaryField(null=True)
    right_middle_img = models.ImageField(upload_to='teachers/fingerprints', default="")
    right_middle_keypoints = models.BinaryField(null=True)
    right_middle_descriptors = models.BinaryField(null=True)
    right_ring_img = models.ImageField(upload_to='teachers/fingerprints', default="")
    right_ring_keypoints = models.BinaryField(null=True)
    right_ring_descriptors = models.BinaryField(null=True)
    right_little_img = models.ImageField(upload_to='teachers/fingerprints', default="")
    right_little_keypoints = models.BinaryField(null=True)
    right_little_descriptors = models.BinaryField(null=True)

    def save(self, *args, **kwargs):
        if self.teacher_status == 'V':
            try:
                img = Img.open(self.face_img)
                img = np.array(img)
            except:
                img = None
            
            if img is not None:
                try:
                    # img = cv2.resize(img, (0, 0), None, 0.25, 0.25)
                    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
                    faces = face_recognition.face_locations(img)
                    print('No. of Faces: ', len(faces))
                    encodings = face_recognition.face_encodings(img, faces)[0]
                    print('Encodings Stored*********         : ', encodings)
                    np_bytes = pickle.dumps(encodings)
                    np_base64 = base64.b64encode(np_bytes)
                    self.face_encodings = np_base64
                except:
                    raise ValidationError('Error processing face image')
            
            # Extracting keypoints from Fingerprint samples and storing in the database
            sift = cv2.SIFT_create()
            fingerprints = []
            try:
                fingerprints.append(np.array(Img.open(self.right_thumb_img)))
            except:
                pass
            try:
                fingerprints.append(np.array(Img.open(self.right_index_img)))
            except:
                pass
            try:
                fingerprints.append(np.array(Img.open(self.right_middle_img)))
            except:
                pass
            try:
                fingerprints.append(np.array(Img.open(self.right_ring_img)))
            except:
                pass
            try:
                fingerprints.append(np.array(Img.open(self.right_little_img)))
            except:
                pass

            encoded_keypoints = []
            encoded_descriptors = []
            for fingerprint in fingerprints:
                keypoints, descriptors = sift.detectAndCompute(fingerprint, None)

                # print('Before*******************')
                # print(keypoints, descriptors)
            
                points_list = []
                for point in keypoints:
                    temp = (point.pt, point.size, point.angle, point.response, point.octave, point.class_id)
                    points_list.append(temp)

                np_bytes = pickle.dumps(points_list)
                encoded_keypoints.append(base64.b64encode(np_bytes))

                np_bytes = pickle.dumps(descriptors)
                encoded_descriptors.append(base64.b64encode(np_bytes))


            try: 
                self.right_thumb_keypoints = encoded_keypoints[0]
                self.right_thumb_descriptors = encoded_descriptors[0]
            except:
                pass
            try:
                self.right_index_keypoints = encoded_keypoints[1]
                self.right_index_descriptors = encoded_descriptors[1]
            except:
                pass
            try:
                self.right_middle_keypoints = encoded_keypoints[2]
                self.right_middle_descriptors = encoded_descriptors[2]
            except:
                pass
            try:
                self.right_ring_keypoints = encoded_keypoints[3]
                self.right_ring_descriptors = encoded_descriptors[3]
            except:
                pass
            try:
                self.right_little_keypoints = encoded_keypoints[4]
                self.right_little_descriptors = encoded_descriptors[4]
            except:
                pass

        super().save(*args, **kwargs)

    def __str__(self):
        if self.teacher_status == 'V':
            return self.teacher_name + " (Visiting)"
        else:
            return self.teacher_name + " (Permanent)"


class TeacherAdminModel(admin.ModelAdmin):
    search_fields=('teacher_name', 'teacher_designation', 'teacher_status', 'user__username', 'user__email')
    list_display = ('user', 'teacher_name', 'teacher_designation', 'teacher_status')


class Attendance(models.Model):
    class Meta:
        verbose_name = _('Teacher Attendance')
        verbose_name_plural = _('Teacher Attendances')
    id = models.AutoField
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, null=True)
    checkin_img = models.ImageField(upload_to='teacher_attendance', null=True, blank=True)
    checkout_img = models.ImageField(upload_to='teacher_attendance', null=True, blank=True)
    checkin_time = models.DateTimeField(null=True)
    checkout_time = models.DateTimeField(null=True)

    def clean(self):
        try:
            already_taken = Attendance.objects.filter(teacher=self.teacher, checkin_time__year=self.checkin_time.year, checkin_time__month=self.checkin_time.month, checkin_time__day=self.checkin_time.day)
            if self.pk:
                already_taken = already_taken.exclude(pk=self.pk)
            if already_taken.exists():
                raise ValidationError("Teacher Attendance instance already exists!")
            if self.checkin_time.date() > datetime.now().date() or self.checkout_time.date() > datetime.now().date():
                raise ValidationError('Error: Date must be less than or equal to today!')
            if self.checkout_time < self.checkin_time:
                raise ValidationError('Error: Check in time is greater than check out time!')
        except:
            pass


class AttendanceAdminModel(admin.ModelAdmin):
    search_fields=('checkin_time', 'checkout_time', 'id', 'teacher__teacher_name', 'teacher__user__username', 'teacher__user__email')
    list_display = ('teacher', 'checkin_time', 'checkout_time')


class PendingRegistration(models.Model):
    id = models.AutoField
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    def __str__(self):
        return self.teacher.teacher_name


class Course(models.Model):  
    id = models.AutoField
    course_code =  models.CharField(max_length=6)
    course_name = models.CharField(max_length=50)
    teacher = models.ForeignKey(Teacher, null=True , on_delete=models.SET_NULL, blank=True)

    def __str__(self):
        if self.teacher is not None:
            return f'{self.course_code} {self.course_name} | {self.teacher.teacher_name}'
        else:
            return f'{self.course_code} {self.course_name}'
    
    def clean(self):
        already_exists = Course.objects.filter(course_code=self.course_code, teacher=self.teacher)
        if self.pk:
            already_exists = already_exists.exclude(pk=self.pk)
        if already_exists.exists():
            raise ValidationError('Course already exists!')


class CourseAdminModel(admin.ModelAdmin):
    search_fields=('course_code', 'course_name')
    list_display = ('course_code', 'course_name', 'teacher')


class ClassRoom(models.Model):
    id=models.AutoField
    room_no = models.IntegerField(unique=True)

    def __str__(self):
        return str(self.room_no)


class ClassRoomAdminModel(admin.ModelAdmin):
    search_fields=('room_no',)
    list_display = ('room_no',)


class ClassTiming(models.Model):
    id = models.AutoField
    start_time = models.TimeField()

templates/progoffice/add_teacher.html
{% extends 'base.html' %}

{% block title %}Register Teacher{% endblock title %}

{% block alert %}
  {% for error in user_form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Error:</span>
      {{ error }}
    </div>
  {% endfor %}

  {% for error in teacher_form.non_field_errors %}
    <div class="alert alert-danger alert-dismissible" role="alert">
      <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      <span class="sr-only">Error:</span>
      {{ error }}
    </div>
  {% endfor %}

  {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
      {% if message.tags == "success" %}
        <span class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>
      {% else %}
        <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      {% endif %}
      
      {{ message }}
    </div>
  {% endfor %}
{% endblock alert %}

{% block body %}
  <!-- /Body Header-->
    <!-- /Register Teacher-->
    <div class="row">
      <div class="col-md-auto"></div>
      <div class="col-md-auto">
        <form method="post" action={% url 'add_teacher' %} enctype="multipart/form-data">
          {% csrf_token %}
          <h1 class="page-header">Register Teacher</h1>
          
          <legend><span class="number">1</span>Sign Up info</legend>
          {{ user_form.as_p }}
        
          <legend><span class="number">2</span>Profile</legend>
          <label class="is-invalid">Name:</label>
          <div class="invalid-feedback">
            {{ teacher_form.teacher_name.errors }}
          </div>
          {{ teacher_form.teacher_name }}

          <label class="is-invalid">Teacher Status:</label>
          <div class="invalid-feedback">
            {{ teacher_form.teacher_status.errors }}
          </div>
          {{ teacher_form.teacher_status }}
          <br><br>

          <label class="is-invalid">Designation:</label>
          <div class="invalid-feedback">
            {{ teacher_form.teacher_designation.errors }}
          </div>
          {{ teacher_form.teacher_designation }} 

          <div id="optional">
            <legend><span class="number">3</span>Upload Face Image</legend>  
            <br>

            <div class="form-outline mb-4">
              <label class="form-label mx-2 is-invalid">Face Image</label>
              <div class="invalid-feedback">
                {{ teacher_form.face_img.errors }}
              </div>
              {{ teacher_form.face_img }}
            </div>
            <br>

            <legend><span class="number">4</span>Upload Fingerprint Samples</legend>  
            <br>

            <div class="form-outline mb-4">
              <label class="form-label mx-2">1</label>
              <div class="invalid-feedback">
                {{ teacher_form.right_thumb_img.errors }}
              </div>
              {{ teacher_form.right_thumb_img }}
            </div>
            <br>

            <div class="form-outline mb-4">
              <label class="form-label mx-2">2</label>
              <div class="invalid-feedback">
                {{ teacher_form.right_index_img.errors }}
              </div>
              {{ teacher_form.right_index_img }}
            </div>
            <br>

            <div class="form-outline mb-4">
              <label class="form-label mx-2">3</label>
              <div class="invalid-feedback">
                {{ teacher_form.right_middle_img.errors }}
              </div>
              {{ teacher_form.right_middle_img }}
            </div>
            <br>

            <div class="form-outline mb-4">
              <label class="form-label mx-2">4</label>
              <div class="invalid-feedback">
                {{ teacher_form.right_ring_img.errors }}
              </div>
              {{ teacher_form.right_ring_img }}
            </div>
            <br>

            <div class="form-outline mb-4">
              <label class="form-label mx-2">5</label>
              <div class="invalid-feedback">
                {{ teacher_form.right_little_img.errors }}
              </div>
              {{ teacher_form.right_little_img }}
            </div>
            <br><br>
          </div>

          <button type="submit">Register</button>

        </form>
      </div>
    <div class="col-md-3"></div>
{% endblock body %}

{% block style %}
  <style>
    @charset "UTF-8";
    /*!
    * Start Bootstrap - SB Admin 2 Bootstrap Admin Theme (https://startbootstrap.com)
    * Code licensed under the Apache License v2.0.
    * For details, see http://www.apache.org/licenses/LICENSE-2.0.
    */
    body {
      background-color: #f8f8f8;
    }

    .errorlist {
      font-size: 14px;
      color: red;
    }

    .invalid-feedback {
      font-size: 14px;
      color: red;
    }

    #wrapper {
      width: 100%;
    }

    #page-wrapper {
      padding: 0 15px;
      min-height: 568px;
      background-color: #fff;
    }

    @media (min-width: 768px) {
      #page-wrapper {
        position: inherit;
        margin: 0 0 0 250px;
        padding: 0 30px;
        border-left: 1px solid #e7e7e7;
      }
    }
    .navbar-top-links {
      margin-right: 0;
    }

    .navbar-top-links li {
      display: inline-block;
    }

    .navbar-top-links li:last-child {
      margin-right: 15px;
    }

    .navbar-top-links li a {
      padding: 15px;
      min-height: 50px;
    }

    .navbar-top-links .dropdown-menu li {
      display: block;
    }

    .navbar-top-links .dropdown-menu li:last-child {
      margin-right: 0;
    }

    .navbar-top-links .dropdown-menu li a {
      padding: 3px 20px;
      min-height: 0;
    }

    .navbar-top-links .dropdown-menu li a div {
      white-space: normal;
    }

    .navbar-top-links .dropdown-messages,
    .navbar-top-links .dropdown-tasks,
    .navbar-top-links .dropdown-alerts {
      width: 310px;
      min-width: 0;
    }

    .navbar-top-links .dropdown-messages {
      margin-left: 5px;
    }

    .navbar-top-links .dropdown-tasks {
      margin-left: -59px;
    }

    .navbar-top-links .dropdown-alerts {
      margin-left: -123px;
    }

    .navbar-top-links .dropdown-user {
      right: 0;
      left: auto;
    }

    .sidebar .sidebar-nav.navbar-collapse {
      padding-right: 0;
      padding-left: 0;
    }

    .sidebar .sidebar-search {
      padding: 15px;
    }

    .sidebar ul li {
      border-bottom: 1px solid #e7e7e7;
    }

    .sidebar ul li a.active {
      background-color: #eee;
    }

    .sidebar .arrow {
      float: right;
    }

    .sidebar .fa.arrow:before {
      content: "";
    }

    .sidebar .active > a > .fa.arrow:before {
      content: "";
    }

    .sidebar .nav-second-level li,
    .sidebar .nav-third-level li {
      border-bottom: 0 !important;
    }

    .sidebar .nav-second-level li a {
      padding-left: 37px;
    }

    .sidebar .nav-third-level li a {
      padding-left: 52px;
    }

    @media (min-width: 768px) {
      .sidebar {
        z-index: 1;
        position: absolute;
        width: 250px;
        margin-top: 51px;
      }

      .navbar-top-links .dropdown-messages,
    .navbar-top-links .dropdown-tasks,
    .navbar-top-links .dropdown-alerts {
        margin-left: auto;
      }
    }
    .btn-outline {
      color: inherit;
      background-color: transparent;
      transition: all 0.5s;
    }

    .btn-primary.btn-outline {
      color: #428bca;
    }

    .btn-success.btn-outline {
      color: #5cb85c;
    }

    .btn-info.btn-outline {
      color: #5bc0de;
    }

    .btn-warning.btn-outline {
      color: #f0ad4e;
    }

    .btn-danger.btn-outline {
      color: #d9534f;
    }

    *, *:before, *:after {
      -moz-box-sizing: border-box;
      -webkit-box-sizing: border-box;
      box-sizing: border-box;
    }
      
    form {
      max-width: 250px;
      margin: 10px auto;
      padding: 10px 20px;
      background: #f4f7f8;
      border-radius: 8px;
    }

    h1 {
      margin: 0 0 25px 0;
      text-align: center;
    }
    h2 {
      text-align: center;
      font-family: 'Nunito', sans-serif;
      font-weight: normal;
      color: #384047;
      font-size: 1rem;
    }
      
    input[type="text"],
    input[type="password"],
    input[type="date"],
    input[type="datetime"],
    input[type="email"],
    input[type="number"],
    input[type="search"],
    input[type="tel"],
    input[type="time"],
    input[type="url"],
    textarea,
    select {
      background: rgba(255,255,255,0.1);
      border: none;
      font-size: 14px;
      height: auto;
      margin: 0;
      outline: 0;
      padding: 15px;
      width: 100%;
      background-color: #e8eeef;
      color: #8a97a0;
      box-shadow: 0 1px 0 rgba(0,0,0,0.03) inset;
      margin-bottom: 30px;
    }

    input[type="radio"],
    input[type="checkbox"] {
      margin: 0 4px 8px 0;
    }

    select {
      padding: 6px;
      height: 28px;
      border-radius: 2px;
    }

    button {
      padding: 17px 37px 16px 37px;
      color: #FFF;
      background-color: #47AB11;
      font-size: 18px;
      text-align: center;
      font-style: normal;
      border-radius: 5px;
      width: 100%;
      border: 1px solid #3ac162;
      border-width: 1px 1px 3px;
      box-shadow: 0 -1px 0 rgba(255,255,255,0.1) inset;
      margin-bottom: 10px;
    }

    fieldset {
      margin-bottom: 5px;
      border: none;
    }

    legend {
      font-size: 1.4em;
      margin-bottom: 10px;
    }

    label {
      display: block;
      margin-bottom: 8px;
    }

    label.light {
      font-weight: 300;
      display: inline;
    }

    .number {
      background-color: #47AB11;
      color: #fff;
      height: 30px;
      width: 30px;
      display: inline-block;
      font-size: 0.8em;
      margin-right: 4px;
      line-height: 30px;
      text-align: center;
      text-shadow: 0 1px 0 rgba(255,255,255,0.2);
      border-radius: 100%;
    }

    @media screen and (min-width: 480px) {

      form {
        max-width: 480px;
      }

    }

    .col-md-auto{
      padding: 5px;
      background: #21a860;
      height: 100%;
    }
  </style>
{% endblock style %}

{% block js %}
  <script>
    $(function () {
      $("input").attr('required', true)
    })
    $(function() {
      $('#id_teacher_status').change(function(){
        let value = $('#id_teacher_status').val();
        if (value == "P"){
          $('#id_face_img').removeAttr('required');
          $('#id_right_thumb_img').removeAttr('required');
          $('#id_right_index_img').removeAttr('required');
          $('#id_right_middle_img').removeAttr('required');
          $('#id_right_ring_img').removeAttr('required');
          $('#id_right_little_img').removeAttr('required');
          $('#optional').hide();
        }
        else if (value == "V"){
          $('#optional').show()
          $("input").attr('required', true)
        }
    });
    })
    $(function() {
      window.scrollTo(0, 0);
      $('input').blur()
      $('#side-menu').metisMenu();

  });

  // Loads the correct sidebar on window load, collapses the sidebar on window resize.
  // Sets the min-height of #page-wrapper to window size
  $(function() {
      $(window).bind("load resize", function() {
          topOffset = 50;
          width = (this.window.innerWidth > 0) ? this.window.innerWidth : this.screen.width;
          if (width < 768) {
              $('div.navbar-collapse').addClass('collapse');
              topOffset = 100; // 2-row-menu
          } else {
              $('div.navbar-collapse').removeClass('collapse');
          }

          height = ((this.window.innerHeight > 0) ? this.window.innerHeight : this.screen.height) - 1;
          height = height - topOffset;
          if (height < 1) height = 1;
          if (height > topOffset) {
              $("#page-wrapper").css("min-height", (height) + "px");
          }
      });

      var url = window.location;
      var element = $('ul.nav a').filter(function() {
          return this.href == url || url.href.indexOf(this.href) == 0;
      }).addClass('active').parent().parent().addClass('in').parent();
      if (element.is('li')) {
          element.addClass('active');
      }
  });
  </script>
{% endblock js %}

templates/progoffice/course_report.html
{% extends 'base.html' %}

{% block title %}Admin | Course Reports{% endblock title %}

{% block body %}
    <div class="row">
        <form method="POST" action={% url 'course_report_admin' %}>
            {% csrf_token %}
            <div class="col-12" style="margin-top: 10px">
                {% comment %} <label for="name">Course</label> {% endcomment %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary" style="margin-top: 10px">Search</i></button>
            </div>
        </form>
        <br>
        {% if attendance_sheet %}
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                <thead bgcolor="#212529" style="color: white">
                    <tr>
                        <th colspan="1000" scope="col">{{ course }}</th>
                    </tr>
                    <tr>
                        <th scope="col">Sr No</th>
                        <th scope="col">Reg#</th>
                        <th scope="col">Student Name</th>
                        {% for class in class_times %}
                            <th scope="col">{{ class }}</th>
                        {% endfor %}
                        <th scope="col">Percentage</th>
                    </tr>
                </thead>
                <tbody>
                    {% for attendance, student, percentage in attendance_sheet %}
                        <tr>
                            <td scope="row">{{ forloop.counter }}</td>
                            <th scope"row">{{ student.reg_no }}</th>
                            <th scope"row">{{ student.student_name }}</th>
                            
                            {% for status in attendance %}
                                <td>{{ status }}</td>
                            {% endfor %}
                            <td>{{ percentage }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
                </table>
            </div>
            <div class="csv-btn" style="margin: 10px">
                <a href="{% url 'generate_course_csv_admin' %}?pk={{ data_obj_pk }}"><button type="submit" class="btn btn-primary">Download CSV</i></button></a>
            </div>
        {% elif course %}
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                <thead bgcolor="#212529" style="color: white">
                    <tr>
                        <th colspan="1000" scope="col">{{ course }}</th>
                    </tr>
                    <tr>
                        <th scope="col">Sr No</th>
                        <th scope="col">Reg#</th>
                        <th scope="col">Student Name</th>
                        <th scope="col">Percentage</th>
                    </tr>
                </thead>
                <tbody>
                    {% for student in students_enrolled %}
                        <tr>
                            <td scope="row">{{ forloop.counter }}</td>
                            <td scope="row">{{ student.reg_no }}</td>
                            <td scope="row">{{ student.student_name }}</td>
                            <td></td>
                        </tr>
                    {% endfor %}
                </tbody>
                </table>
            </div>
            {% comment %} <div class="csv-btn"> {% endcomment %}
            <a href="{% url 'generate_course_csv_admin' %}?pk={{ data_obj_pk }}"><button type="submit" class="btn btn-primary">Download CSV</i></button></a>
            {% comment %} </div> {% endcomment %}
            {% endif %}
        </div>
    </div>
{% endblock body %}

{% block js %}
    <script>
        $(function() {
        $('#side-menu').metisMenu();
        });

        // Loads the correct sidebar on window load, collapses the sidebar on window resize.
        // Sets the min-height of #page-wrapper to window size

        $(function() {
            $(window).bind("load resize", function() {
                topOffset = 50;
                width = (this.window.innerWidth > 0) ? this.window.innerWidth : this.screen.width;
                if (width < 768) {
                    $('div.navbar-collapse').addClass('collapse');
                    topOffset = 100; // 2-row-menu
                } else {
                    $('div.navbar-collapse').removeClass('collapse');
                }

                height = ((this.window.innerHeight > 0) ? this.window.innerHeight : this.screen.height) - 1;
                height = height - topOffset;
                if (height < 1) height = 1;
                if (height > topOffset) {
                    $("#page-wrapper").css("min-height", (height) + "px");
                }
            });

            var url = window.location;
            var element = $('ul.nav a').filter(function() {
                return this.href == url || url.href.indexOf(this.href) == 0;
            }).addClass('active').parent().parent().addClass('in').parent();
            if (element.is('li')) {
                element.addClass('active');
            }
        });
    </script>
{% endblock js %}
    